# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sfi0p_i3o510tzZgxTN4OXPiZ4sS1wGi

Comparing the rank of a 3*3 matrix using the echolen form
"""

import torch

"""Let us make a matrix of a size, say 3*3"""

a=torch.tensor([[2.,3,4],[5,4,3],[6,3,5]])
print(a)

"""Let's now reduce it to the echlon form by making the first element 1"""

div=a[0][0]
a[0]=a[0]/div
print(a)

"""Let's now make the element below the first element equal to zero."""

a[1]=a[1]-a[1][0]*a[0]
print(a)

"""Similarly we continue for the next element"""

a[2]=a[2]-a[2][0]*a[0]
print(a)

"""Now let's make the element at the last position equal to 0"""

a[2]=a[2]-(a[1]*a[2][1]/a[1][1])
print(a)

"""Calculate the rank of the matrix"""

if(torch.equal(a[2],torch.zeros(3))):
 print("rank=",2)
else:
  print("rank=",3)